sonar.organization=ntrix
sonar.projectKey=ntrix_amazin-be

sonar.sources=auth,controllers,middleware,models,routes,app.js,server.js
sonar.exclusions=tests/**

sonar.tests=tests
sonar.test.inclusions=tests/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
